### PR TITLE
Add [tool.poetry] section to pyproject.toml

### PR DESCRIPTION
**Pull request by anseljh**
A dependent project was complaining about its absence, so I added it.

### CODE REVIEW

**Comment by mlissner** [comment]
That's a bit weird. What tool? We don't use Poetry for this project, I don't think?

**Comment by anseljh** [comment]
I'd added this project as a dependency for a new project based on the repo
template, which does use Poetry, or at least I used Poetry in it. Adding
this made its complaints go away. 🤷‍♂️

**Comment by mlissner** [comment]
Sorry, with packaging stuff I like to proceed pretty carefully. Do you have steps to reproduce for this or the error you saw? 

If we add these tweaks, we'll have a setup.py file and a pyproject.toml file, both of which have the version number, which feels like an anti-pattern. (We also tag our git commits with the version, which makes it three places, not great!)

**Comment by anseljh** [comment]
All good concerns! I'll try to reproduce it in a new repo and will share that back here.

**Comment by anseljh** [comment]
Don't think we need this after all! Not sure where I messed up, but this seems to not be an issue if you're more careful than I was.

**Comment by mlissner** [comment]
Whew, good. I was not looking forward to getting the poetry maintainers to fix this!

**Pull request closed without merging**
